;;; List of packages I want any new setup to automatically install
;; (require-package 'melpa)
(require-package 'ag)
(require-package 'auctex)
(require-package 'auto-complete)
;; (require-package 'auto-complete-clang)
(require-package 'auto-highlight-symbol)
(require-package 'cl-lib)
(require-package 'color-theme)
(require-package 'company)
;; (require-package 'company-quickhelp)
;; (require-package 'direx)
(require-package 'diff-hl)
(require-package 'drag-stuff)
(require-package 'dtrt-indent)
(require-package 'ecb)
;; (require-package 'electric-case)
(require-package 'epc)
(require-package 'expand-region)
(require-package 'fill-column-indicator)
(require-package 'find-file-in-repository)
(require-package 'git-gutter)
(require-package 'glsl-mode)
(require-package 'helm-ls-git)
(require-package 'hideshowvis)
(require-package 'highlight-indentation)
(require-package 'highlight-parentheses)
(require-package 'highlight-symbol)
(require-package 'icicles)
(require-package 'jedi)
(require-package 'magit)
(require-package 'markdown-mode)
(require-package 'neotree)
(require-package 'org)
;; (require-package 'phi-rectangle)
(require-package 'popup)
(require-package 'python-environment)
(require-package 'smartparens)
(require-package 'sr-speedbar)
;; (require-package 'tabbar)
;; (require-package 'yafolding)
